version: '3.1' # specify docker-compose version

# Define the services/containers to be run
services:
  mongo-database: # name of the third service
    image: mongo # specify image to build container from
    environment:
      - MONGO_INITDB_DATABASE=angular7crud
    ports:
      - "27017:27017" # specify port forewarding
    #volumes:
    #  - ./mongo-volume:/data/db

  express: #name of the second service
    container_name: backendContainer
    build: api # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - mongo-database

  angular: # name of the first service
    container_name: clientContainer
    build: ./ # specify the directory of the Dockerfile
    ports:
      - "4200:80" # specify port forewarding

  nginx:
    container_name: nginxContainer
    build: ./nginx
    ports:
      - "80:80"
    links:
      - angular
      - express

