version: '3.1' # specify docker-compose version

# Define the services/containers to be run
services:
  mongo-database: # name of the third service
    container_name: dbContainer
    image: mongo # specify image to build container from
    environment:
      - MONGO_INITDB_DATABASE=angular7crud
    ports:
      - "27117:27017" # specify port forewarding
    volumes:
      - ./mongo-volume:/data/db

  express: #name of the second service
    container_name: backendContainer
    build: api # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  angular: # name of the first service
    container_name: clientContainer
    build: ./ # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding